-- Teil 2/N: Primary Keys, Unique, Foreign Keys, Check Constraints (in dieser Reihenfolge wichtig)

ALTER TABLE ONLY public.app_settings ADD CONSTRAINT app_settings_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.appointments ADD CONSTRAINT appointments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.bookings ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.calendar_feeds ADD CONSTRAINT calendar_feeds_pkey PRIMARY KEY (owner);
ALTER TABLE ONLY public.deletion_log ADD CONSTRAINT deletion_log_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.device_tokens ADD CONSTRAINT device_tokens_pkey PRIMARY KEY (owner, token);
ALTER TABLE ONLY public.document_counters ADD CONSTRAINT document_counters_pkey PRIMARY KEY (school_id, kind, year);
ALTER TABLE ONLY public.exam_slots ADD CONSTRAINT exam_slots_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.interessenten ADD CONSTRAINT interessenten_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.ki_usage ADD CONSTRAINT ki_usage_pkey PRIMARY KEY (uid, day, feature);
ALTER TABLE ONLY public.lesson_reflections ADD CONSTRAINT lesson_reflections_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.payer_lookup_throttle ADD CONSTRAINT payer_lookup_throttle_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.profiles ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.public_chat_usage ADD CONSTRAINT public_chat_usage_pkey PRIMARY KEY (booking_code, day, feature);
ALTER TABLE ONLY public.public_enroll_usage ADD CONSTRAINT public_enroll_usage_pkey PRIMARY KEY (booking_code, day);
ALTER TABLE ONLY public.route_templates ADD CONSTRAINT route_templates_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.schools ADD CONSTRAINT schools_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.staff_files ADD CONSTRAINT staff_files_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.student_files ADD CONSTRAINT student_files_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.student_login_throttle ADD CONSTRAINT student_login_throttle_pkey PRIMARY KEY (throttle_key);
ALTER TABLE ONLY public.students ADD CONSTRAINT students_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.templates ADD CONSTRAINT templates_pkey PRIMARY KEY (owner);
ALTER TABLE ONLY public.theory_attendance ADD CONSTRAINT theory_attendance_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.theory_questions ADD CONSTRAINT theory_questions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.theory_resources ADD CONSTRAINT theory_resources_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.videos ADD CONSTRAINT videos_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.vouchers ADD CONSTRAINT vouchers_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.widget_tokens ADD CONSTRAINT widget_tokens_pkey PRIMARY KEY (owner);

ALTER TABLE ONLY public.calendar_feeds ADD CONSTRAINT calendar_feeds_token_key UNIQUE (token);
ALTER TABLE ONLY public.lesson_reflections ADD CONSTRAINT lesson_reflections_student_id_lesson_id_key UNIQUE (student_id, lesson_id);
ALTER TABLE ONLY public.profiles ADD CONSTRAINT profiles_email_key UNIQUE (email);
ALTER TABLE ONLY public.theory_attendance ADD CONSTRAINT theory_attendance_appt_id_student_id_key UNIQUE (appt_id, student_id);
ALTER TABLE ONLY public.vouchers ADD CONSTRAINT vouchers_code_key UNIQUE (code);
ALTER TABLE ONLY public.widget_tokens ADD CONSTRAINT widget_tokens_token_key UNIQUE (token);

ALTER TABLE ONLY public.appointments ADD CONSTRAINT appointments_owner_fkey FOREIGN KEY (owner) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.bookings ADD CONSTRAINT bookings_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.calendar_feeds ADD CONSTRAINT calendar_feeds_owner_fkey FOREIGN KEY (owner) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.deletion_log ADD CONSTRAINT deletion_log_deleted_by_fkey FOREIGN KEY (deleted_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.deletion_log ADD CONSTRAINT deletion_log_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.device_tokens ADD CONSTRAINT device_tokens_owner_fkey FOREIGN KEY (owner) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.document_counters ADD CONSTRAINT document_counters_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.exam_slots ADD CONSTRAINT exam_slots_owner_fkey FOREIGN KEY (owner) REFERENCES auth.users(id);
ALTER TABLE ONLY public.exam_slots ADD CONSTRAINT exam_slots_student_id_fkey FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.interessenten ADD CONSTRAINT interessenten_owner_fkey FOREIGN KEY (owner) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.ki_usage ADD CONSTRAINT ki_usage_uid_fkey FOREIGN KEY (uid) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.lesson_reflections ADD CONSTRAINT lesson_reflections_owner_fkey FOREIGN KEY (owner) REFERENCES auth.users(id);
ALTER TABLE ONLY public.lesson_reflections ADD CONSTRAINT lesson_reflections_student_id_fkey FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.profiles ADD CONSTRAINT profiles_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id);
ALTER TABLE ONLY public.route_templates ADD CONSTRAINT route_templates_proposed_by_fkey FOREIGN KEY (proposed_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.staff_files ADD CONSTRAINT staff_files_instructor_uid_fkey FOREIGN KEY (instructor_uid) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.staff_files ADD CONSTRAINT staff_files_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES auth.users(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.student_files ADD CONSTRAINT student_files_owner_fkey FOREIGN KEY (owner) REFERENCES profiles(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.student_files ADD CONSTRAINT student_files_student_id_fkey FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.students ADD CONSTRAINT students_owner_fkey FOREIGN KEY (owner) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.templates ADD CONSTRAINT templates_owner_fkey FOREIGN KEY (owner) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.theory_attendance ADD CONSTRAINT theory_attendance_appt_id_fkey FOREIGN KEY (appt_id) REFERENCES appointments(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.theory_attendance ADD CONSTRAINT theory_attendance_owner_fkey FOREIGN KEY (owner) REFERENCES auth.users(id);
ALTER TABLE ONLY public.theory_attendance ADD CONSTRAINT theory_attendance_student_id_fkey FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.theory_resources ADD CONSTRAINT theory_resources_proposed_by_fkey FOREIGN KEY (proposed_by) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.videos ADD CONSTRAINT videos_owner_fkey FOREIGN KEY (owner) REFERENCES auth.users(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.videos ADD CONSTRAINT videos_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.vouchers ADD CONSTRAINT vouchers_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id);
ALTER TABLE ONLY public.vouchers ADD CONSTRAINT vouchers_redeemed_student_id_fkey FOREIGN KEY (redeemed_student_id) REFERENCES students(id) ON DELETE SET NULL;
ALTER TABLE ONLY public.vouchers ADD CONSTRAINT vouchers_school_id_fkey FOREIGN KEY (school_id) REFERENCES schools(id) ON DELETE CASCADE;
ALTER TABLE ONLY public.widget_tokens ADD CONSTRAINT widget_tokens_owner_fkey FOREIGN KEY (owner) REFERENCES profiles(id) ON DELETE CASCADE;

ALTER TABLE ONLY public.app_settings ADD CONSTRAINT app_settings_singleton CHECK ((id = 1));
ALTER TABLE ONLY public.document_counters ADD CONSTRAINT document_counters_kind_check CHECK ((kind = ANY (ARRAY['invoice'::text, 'receipt'::text, 'contract'::text])));
ALTER TABLE ONLY public.exam_slots ADD CONSTRAINT exam_slots_art_check CHECK ((art = ANY (ARRAY['theorie'::text, 'praxis'::text])));
ALTER TABLE ONLY public.exam_slots ADD CONSTRAINT exam_slots_status_check CHECK ((status = ANY (ARRAY['frei'::text, 'vergeben'::text, 'abgesagt'::text])));
ALTER TABLE ONLY public.payer_lookup_throttle ADD CONSTRAINT payer_lookup_throttle_id_check CHECK (id);
ALTER TABLE ONLY public.theory_resources ADD CONSTRAINT theory_resources_kind_check CHECK ((kind = ANY (ARRAY['methode'::text, 'medium'::text, 'kontrolle'::text])));
ALTER TABLE ONLY public.theory_resources ADD CONSTRAINT theory_resources_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])));
ALTER TABLE ONLY public.vouchers ADD CONSTRAINT vouchers_betrag_check CHECK ((betrag > (0)::numeric));
ALTER TABLE ONLY public.vouchers ADD CONSTRAINT vouchers_status_check CHECK ((status = ANY (ARRAY['offen'::text, 'eingeloest'::text, 'storniert'::text])));
